Tabを実装
AirTotes/AirTote pull request #99
Opened 2022-08-24 07:17 UTC by kojdai

残りのタスク

- [x] 残りのページを元のページから各タブに移動
- [x] 天気のページをTwoPaneViewを使って見やすく実装
- [x] 設定ページを歯車のみのタブを作成
- [ ] MoreタブにTwoPaneViewを使って残りのページを実装

resolves #22
resolves #115

2022-08-28 18:48 UTC, TetsuOtter reviewed
Suggestした変更のほか、XMLのフォーマットについて、`Pages/ThirdPartyLicenses.xaml`のような形に合わせていただけると嬉しいです。

また、ローカルで`dotnet format`と実行して、ファイルフォーマットを整えたコミットもお願いします。

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/AirTote.csproj
> +		<None Remove="Assets\Raw\ImagerySource.csv" />
この設定記述は不要なので削除してください。

```suggestion
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/AirTote.csproj
> +	</ItemGroup>
この設定記述は不要なので削除してください。

```suggestion
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/Pages/TabChild/More.xaml
> +			 xmlns:PPR="clr-namespace:AirTote.Pages.ReservePages"
```suggestion
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/Pages/TabChild/More.xaml.cs
> +	}
意図した改行でしょうか?  この部分に空行を追加しても読みやすさには貢献しないように思えるため、削除をお願いします。

```suggestion
	public More()
	{
		InitializeComponent();
	}
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/Services/ImagerySourceReader.cs
> +	public string URL { get; set; }
バグ防止のため、dotnetからの警告に従って初期値を設定してください。

```suggestion
	public string GroupName { get; set; } = "";
	public string ShortTitle { get; set; } = "";
	public string FullTitle { get; set; } = "";
	public string URL { get; set; } = "";
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/Services/ImagerySourceReader.cs
> +	public async Task<string> ReadTextFileAsync(string filePath)
インスタンスメンバーにアクセスしていないため、`static`にしてください。

```suggestion
	public static async Task<string> ReadTextFileAsync(string filePath)
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/Services/ImagerySourceReader.cs
> +	public async Task<List<ImagerySourceReader>> ReadCsvFileAsync(string filePath)
インスタンスメンバーにアクセスしていないため、`static`にしてください。

```suggestion
	public static async Task<List<ImagerySourceReader>> ReadCsvFileAsync(string filePath)
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/Services/OpenBrowserCommand.cs
> +	}
```suggestion
			=> parameter is not null;
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/TabMainPage.xaml.cs
> +[XamlCompilation(XamlCompilationOptions.Compile)]
```suggestion
```

2022-08-28 18:48 UTC, TetsuOtter commented on AirTote/TabMainPage.xaml.cs
> +namespace AirTote.Pages;
名前空間は、なるべくディレクトリ構成とあわせてください。

```suggestion
namespace AirTote;
```

2022-08-30 14:48 UTC, konakahayato commented on AirTote/Assets/Raw/ImagerySource.csv
> +空域の情報,下層悪天予想図（詳細版）,下層悪天予想図（詳細版）,https:www.data.jma.go.jp/airinfo/data/awfo_low-level_detailed-sigwx.html,true
タブ選択時にクラッシュ発生

2022-08-30 14:50 UTC, konakahayato commented on AirTote/Assets/Raw/ImagerySource.csv
> +SIGチャート２４時間予想図,SIGWXCHARTS,SIGWXCHARTS,http:www.bom.gov.au/aviation/charts/sigwx/,true
タブ選択時にクラッシュ発生

2022-08-31 13:32 UTC, kojdai commented on AirTote/Assets/Raw/ImagerySource.csv
> +実況,AXJP130・140,［AXJP130・140］高層断面図,https://n-kishou.com/ee/exp/exp01.html?cd=axjp140&amp;cat=e1,false
ShotTitleとFullTitleが一致している場合(スプレッドシートの148行目~173行目)はどのようにすれば良いでしょうか？

2022-09-01 15:31 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +アメダス,,日照時間,https://www.jma.go.jp/bosai/map.html#5/34.315/142.393/&elem=sun1h&contents=amedas&interval=60https://www.jma.go.jp/bosai/map.html#5/34.315/142.393/&elem=sun1h&contents=amedas&interval=60,t
```suggestion
アメダス,,日照時間,https://www.jma.go.jp/bosai/map.html#5/34.315/142.393/&elem=sun1h&contents=amedas&interval=60,true
```

2022-09-02 11:48 UTC, TetsuOtter commented
@kojdai csvをうまく処理できないバグは対応完了しました

ほかタスク (既出は除く)

- [ ] `ShortTitle`が存在しないrecordは、`Text`相当のところに`FullText`を表示させる
- [ ] グループヘッダがうまく表示されていないバグの修正
- [ ] (可能であれば) `ViewCell`を活用し、ブラウザで開くデータと右Paneで表示するデータを見分けられるようにする
- [ ] (可能であれば) `ViewCell`を活用し、情報源を表示させるようにする

「可能であれば」なタスクは、このPRでは対応せずに、EnhancementとしてIssueを立てて後日対応でも構いません。

2022-09-05 01:56 UTC, TetsuOtter requested changes

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +数値天気予報図,, [12UTC]日本850hPa相当温位・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxjp854_12.pdf,true
不要なスペースを削除してください

```suggestion
数値天気予報図,,[00UTC]アジア太平洋250hPa高度・気温・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa252_00.pdf,true
数値天気予報図,,[00UTC]アジア太平洋300hPa高度・気温・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa302_00.pdf,true
数値天気予報図,,[00UTC]アジア太平洋400hPa高度・気温・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa402_00.pdf,true
数値天気予報図,,[00UTC]アジア太平洋500hPa高度・気温・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa502_00.pdf,true
数値天気予報図,,[00UTC]極東850hPa気温・風、700hPa上昇流／700hPa湿数、500hPa気温予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe5782_00.pdf,true
数値天気予報図,,[00UTC]極東地上気圧・風・降水量／500hPa高度・渦度予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe502_00.pdf,true
数値天気予報図,,[00UTC]日本850hPa相当温位・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxjp854_00.pdf,true
数値天気予報図,,[12UTC]アジア太平洋250hPa高度・気温・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa252_12.pdf,true
数値天気予報図,,[12UTC]アジア太平洋300hPa高度・気温・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa302_12.pdf,true
数値天気予報図,,[12UTC]アジア太平洋400hPa高度・気温・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa402_12.pdf,true
数値天気予報図,,[12UTC]アジア太平洋500hPa高度・気温・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa502_12.pdf,true
数値天気予報図,,[12UTC]極東850hPa気温・風、700hPa上昇流／700hPa湿数、500hPa気温予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe5782_12.pdf,true
数値天気予報図,,[12UTC]極東地上気圧・風・降水量／500hPa高度・渦度予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe502_12.pdf,true
数値天気予報図,,[12UTC]日本850hPa相当温位・風予想図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxjp854_12.pdf,true
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +FXFE FUFE 12Z,,FXFE FUFE 12Z,https://www.jma.go.jp/jmh/wmapimgs/fxfe57782_12_large.png,true
Group Nameに時間を含めないで下さい。また、GroupNameやデータの名前が違うような気がします。

```suggestion
FXFE,,FXFE572/FXFE782 [00UTC],https://www.jma.go.jp/jmh/wmapimgs/fxfe57782_00_large.png,true
FXFE,,FXFE572/FXFE782[12UTC],https://www.jma.go.jp/jmh/wmapimgs/fxfe57782_12_large.png,true
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +実況,AUPQ78,アジア850hPa700hPa解析図,https://n-kishou.com/ee/exp/exp01.html?cd=aupq78,false
気象庁発表のものと重複しているため、削除してください

```suggestion
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +高層天気図,,[12UTC]高層断面図（風・気温・露点等）東経130度／140度解析,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axjp140_12.pdf,true
不要な空白を削除し、ShortTitleが存在する場合はShortTitleを記載してください。]

```suggestion
高層天気図,AUXN50 [12UTC],北半球500hPa高度・気温天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/auxn50_12.pdf,true
高層天気図,FEAS50 [12UTC],アジア地上気圧、850hPa気温／500hPa高度・渦度天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/feas50_12.pdf,true
高層天気図,AUPA20 [00UTC],アジア太平洋200hPa高度・気温・風・圏界面天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupa20_00.pdf,true
高層天気図,AUPA25 [00UTC],アジア太平洋250hPa高度・気温・風天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupa25_00.pdf,true
高層天気図,AUPN30 [00UTC],北太平洋300hPa高度・気温・風天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupn30_00.pdf,true
高層天気図,AUPQ35 [00UTC],アジア500hPa・300hPa高度・気温・風・等風速線天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupq35_00.pdf,true
高層天気図,AUPQ78 [00UTC],アジア850hPa・700hPa高度・気温・風・湿数天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupq78_00.pdf,true
高層天気図,AXFE578 [00UTC],極東850hPa気温・風、700hPa上昇流／500hPa高度・渦度天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axfe578_00.pdf,true
高層天気図,AXJP140 [00UTC],高層断面図（風・気温・露点等）東経130度／140度解析,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axjp140_00.pdff,true
高層天気図,AUPA20 [12UTC],アジア太平洋200hPa高度・気温・風・圏界面天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupa20_12.pdf,true
高層天気図,AUPA25 [12UTC],アジア太平洋250hPa高度・気温・風天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupa25_12.pdf,true
高層天気図,AUPN30 [12UTC],北太平洋300hPa高度・気温・風天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupn30_12.pdf,true
高層天気図,AUPQ35 [12UTC],アジア500hPa・300hPa高度・気温・風・等風速線天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupq35_12.pdf,true
高層天気図,AUPQ78 [12UTC],アジア850hPa・700hPa高度・気温・風・湿数天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupq78_12.pdf,true
高層天気図,AXFE578 [12UTC],極東850hPa気温・風、700hPa上昇流／500hPa高度・渦度天気図,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axfe578_12.pdf,true
高層天気図,AXJP140 [12UTC],高層断面図（風・気温・露点等）東経130度／140度解析,https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axjp140_12.pdf,true
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +衛星画像,,High-resolutionCloudAnalysisIndex(HCAI),https://www.data.jma.go.jp/omaad/rsmc_nowcast/en/hcai/#zoom:3/lat:15.707663/lon:140.097656/colordepth:normal/elements:htc,true
```suggestion
衛星画像,HCAI,High-resolution Cloud Analysis Index,https://www.data.jma.go.jp/omaad/rsmc_nowcast/en/hcai/#zoom:3/lat:15.707663/lon:140.097656/colordepth:normal/elements:htc,true
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +エマグラム ,,(Skew-T)エマグラム ,https://www.tono2.net/skew/,false
不要なスペースは削除してください
```suggestion
エマグラム,,北アメリカ,http://weather.uwyo.edu/upperair/naconf.html,false
エマグラム,,(University of wayoming)南アメリカ,http://weather.uwyo.edu/upperair/samer.html,false
エマグラム,,(University of wayoming)南太平洋,http://weather.uwyo.edu/upperair/pac.html,false
エマグラム,,(University of wayoming)ニュージーランド,http://weather.uwyo.edu/upperair/nz.html,false
エマグラム,,(University of wayoming)南極,http://weather.uwyo.edu/upperair/ant.html,false
エマグラム,,(University of wayoming)北極,http://weather.uwyo.edu/upperair/np.html,false
エマグラム,,(University of wayoming)ヨーロッパ,http://weather.uwyo.edu/upperair/europe.html,false
エマグラム,,(University of wayoming)アフリカ,http://weather.uwyo.edu/upperair/africa.html,false
エマグラム,,(University of wayoming)中央アジア,http://weather.uwyo.edu/upperair/africa.html,false
エマグラム,,(University of wayoming)南東アジア,http://weather.uwyo.edu/upperair/seasia.html,false
エマグラム,,(SunnySpot)全国,https://www.sunny-spot.net/emagram/index.html?area=0,false
エマグラム,,(SunnySpot)北海道,https://www.sunny-spot.net/emagram/index.html?area=1,false
エマグラム,,(SunnySpot)東北,https://www.sunny-spot.net/emagram/index.html?area=2,false
エマグラム,,(SunnySpot)関東甲信,https://www.sunny-spot.net/emagram/index.html?area=3,false
エマグラム,,(SunnySpot)北陸,https://www.sunny-spot.net/emagram/index.html?area=4,false
エマグラム,,(SunnySpot)東海,https://www.sunny-spot.net/emagram/index.html?area=5,false
エマグラム,,(SunnySpot)近畿,https://www.sunny-spot.net/emagram/index.html?area=6,false
エマグラム,,(SunnySpot)中国,https://www.sunny-spot.net/emagram/index.html?area=7,false
エマグラム,,(SunnySpot)四国,https://www.sunny-spot.net/emagram/index.html?area=8,false
エマグラム,,(SunnySpot)九州北部,https://www.sunny-spot.net/emagram/index.html?area=9,false
エマグラム,,(SunnySpot)九州南部,https://www.sunny-spot.net/emagram/index.html?area=10,false
エマグラム,,(SunnySpot)南西諸島,https://www.sunny-spot.net/emagram/index.html?area=11,false
エマグラム,,(Skew-T)エマグラム ,https://www.tono2.net/skew/,false
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +風情報,,風情報Windy,"https://www.windy.com/?34.398,132.452,5",false
```suggestion
風情報,,Windy,"https://www.windy.com/?34.398,132.452,5",false
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +SNOWTAM滑走路面状態,,SNOWTAM滑走路面状態,https://ok0358.com/snowtam/index.php,false
滑走路面状態だと、「空港の情報」の方が適切では…?
```suggestion
空港の情報,SNOWTAM,滑走路面状態,https://ok0358.com/snowtam/index.php,false
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +ライブカメラ,,ライブカメラ,http://weather.jal.co.jp/livecam/index.html,false
もう少し詳しいTitleにして下さい

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +ライブカメラ,2RJCC,新千歳空港,http://www.hbc.jp/info-cam/shinchitose.html,false
```suggestion
ライブカメラ,RJCC2,新千歳空港,http://www.hbc.jp/info-cam/shinchitose.html,false
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +ライブカメラ,,那覇ROAH石垣,http://weather.jal.co.jp/livecam/spot.html?camid=410000154,false
```suggestion
ライブカメラ,ROAH,那覇空港,http://weather.jal.co.jp/livecam/spot.html?camid=410000154,false
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Assets/Raw/ImagerySource.csv
> +SIGチャート２４時間予想図,,SIGWXCHARTS,http://www.bom.gov.au/aviation/charts/sigwx/,true
オーストラリアの政府機関の情報は扱いがわからないため、念のため`IsPublic`を`false`にしておいてください。

```suggestion
SIGチャート２４時間予想図,,SIGWXCHARTS,http://www.bom.gov.au/aviation/charts/sigwx/,false
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/App.xaml.cs
> +		MainPage = new AirTote.TabMainPage();
わざわざ`AirTote.TabMainPage`みたいにせずとも、同じnamespaceに属するので、下みたいな感じに書けます。

```suggestion
		MainPage = new TabMainPage();
```

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/Pages/TabChild/More.xaml
> +					Clicked="Button_Clicked_4"/>
TODO: スタイル修正

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/TabMainPage.xaml
> +		</Tab>-->
- 可能なら: スタイルの修正
- 可能なら: ハリボテページへのリンク無効化

2022-09-05 01:56 UTC, TetsuOtter commented on AirTote/TabMainPage.xaml.cs
> +		//=> this.ShowPopupAsync(new FlyoutMenuPopup());
不要なコメントアウト部分は削除してしまいましょう

```suggestion
```

2022-09-09 08:08 UTC, TetsuOtter submitted a review, later dismissed

2022-09-09 12:16 UTC, TetsuOtter approved these changes

2022-09-09 15:02 UTC, merged